fixed github actions by adding all the binaries in the environnment variables

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -8,7 +8,9 @@ on:
       - 'ga-ignore-*'
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2027/B-CPE-200-MPL-2-1-corewar-marlon.pegahi.git"
-  EXECUTABLES: "asm/asm"
+  EXECUTABLES: "asm/asm,corewar/corewar"
+  EXECUTABLES1: "asm/asm"
+  EXECUTABLES2: "corewar/corewar"
   ALLOWED_FUNCS: "open,fopen,read,fread,write,fwrite,getline,lseek,fseek,close,fclose,malloc,realloc,free,exit"
 jobs:
   check_coding_style:
@@ -68,8 +70,8 @@ jobs:
             fi
             done
         continue-on-error: false
-  check_banned_functions:
-    name: Banned Functions Checker
+  check_banned_functions_asm:
+    name: Banned Functions Checker Asm
     runs-on: ubuntu-latest
     needs: check_program_compilation
     container:
@@ -89,7 +91,48 @@ jobs:
             
             while read func_name; do
                 all_func+=("$func_name")
-            done < <(nm -D $EXECUTABLES | grep -oP '\b(?!__)[a-zA-Z_]+(?=@)')
+            done < <(nm -D $EXECUTABLES1 | grep -oP '\b(?!__)[a-zA-Z_]+(?=@)')
+            
+            for func in "${all_func[@]}"; do
+                is_banned=1
+                for allowed_func in "${list[@]}"; do
+                    if [ "$func" == "$allowed_func" ]; then
+                        is_banned=0
+                    fi
+                done
+                if [ $is_banned == 1 ]; then
+                    banned_func+=("$func")
+                fi
+            done
+
+            for banned in "${banned_func[@]}"; do
+                exit_status=84
+                echo "::error title=MAJOR error::Banned function $banned used"
+            done
+            exit $exit_status
+        continue-on-error: false
+  check_banned_functions_corewar:
+    name: Banned Functions Checker Corewar
+    runs-on: ubuntu-latest
+    needs: check_banned_functions_asm
+    container:
+      image: epitechcontent/epitest-docker:latest
+    steps:
+      - uses: actions/checkout@main
+        with:
+          fetch-depth: 0
+      - run: make
+      - run: make clean
+      - run: |
+            IFS=',' read -ra list <<< "$ALLOWED_FUNCS"
+            banned_func=()
+            is_banned=0
+            all_func=()
+            exit_status=0
+            
+            while read func_name; do
+                all_func+=("$func_name")
+            done < <(nm -D $EXECUTABLES2 | grep -oP '\b(?!__)[a-zA-Z_]+(?=@)')
             
             for func in "${all_func[@]}"; do
                 is_banned=1
@@ -112,7 +155,7 @@ jobs:
   push_to_mirror:
     name: Mirror Pusher
     runs-on: ubuntu-latest
-    needs: check_banned_functions
+    needs: check_banned_functions_corewar
     if: github.event_name == 'push'
     steps:
       - uses: actions/checkout@main
